language: java
jdk:
  - openjdk11
#  blacklist
branches:
  except:
    - gh-pages
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
   - ./gradlew clean asciidoc
after_success:
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && ./deploy_ghpages.sh'
