= jMonkeyEngine Dokumentation
:revdate: Mai 2020
:experimental:
:keywords: documentation, sdk, install
:link-javadoc: https://javadoc.jmonkeyengine.org
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


//This documentation wiki contains installation and configuration guides,
Diese Doku liefert eine Anleitung für die Installation und Konfiguration, jME Programmiertutorials und andere Information die ihnen helfen werden ihr Gaming-projekt zum laufen zu bringen.
//jME coding tutorials and other information that will help you get your game project going.
Sie können die Suchfunktion am oberen Ende jeder Wikiseite benutzen um das gesamte Wiki zu durchforsten.
//You can search the contents of this wiki using the "`Wiki`" menu search box at the top of each page.

Sie sind auch dazu angehalten Verbesserungsvorschläge bei dieser Übersetzung des "'Wikis'" mit dem Menü "'Edit'"  icon:pencil-square[role="blue"] und "`Add`" icon:plus-square[role="blue"] zu geben. Sie müssen in GitHub eingeloggt sein um das wiki zu bearbeiten.
//You are also very welcome to fix mistakes or spelling as well as unclear paragraphs using the "`Wiki`" menu "`Edit`" icon:pencil-square[role="blue"] and "`Add`" icon:plus-square[role="blue"] buttons. You have to be logged into GitHub to edit the wiki.
Hier können sie mehr über das Editieren und <<documentation#contribute#,Beitragen>> erfahren.
//You can learn more about editing and contributing under the <<documentation#contribute#,Contribute>> heading.

//TIP: This is an Admonition. You will see many of these scattered throughout the Wiki. See the <<wiki/admonitions#,Admonition Definitions>> for the meaning of this and all the other Admonitions.
TIP: Das ist ein Warnhinweis. Es wird an verschiedenen Stellen solche im Wiki geben. Unter <<wiki/admonitions#,Warnhinweise>> finden sie die Bedeutung dieser.

== Forum

Das link:http://hub.jmonkeyengine.org/[Forum] ist die erste Anlaufstelle um Fehler zu melden, Beiträge zu leisten, den Wiki Inhalt zu diskutieren
//The link:http://hub.jmonkeyengine.org/[forum] is your first stop when reporting bugs, making contributions, discussing wiki content,
oder auch sonst, wenn sie die Antworten auf ihre Fragen im Wiki und den Forenarchiv nicht finden.
//or anything else that you can't get the answer for by reading the wiki or searching the forum archives.
Sie werden dort eine freundliche und einladende Atmosphäre vorfinden, aber bevor sie posten beachten sie die folgenden 2 Regeln.
//You will find it to be a friendly and inviting place to have discussions, but before posting, there are two minor rules you will need to observe.

.  Für Fragen die Quelltext beinhalten, lernen sie link:https://hub.jmonkeyengine.org/t/how-to-type-code-blocks/31155[wie man Programmblöcke einfügt]. Sie werden sonst statt einer Anwort höchstens eine Rüge erhalten. In den <<github_tips#,Github Tipps>> steht wie sie Links in ihre Beiträge einfügen können.
.  link:https://hub.jmonkeyengine.org/t/uploading-pictures-and-changing-avatars-is-disabled/39520[Hochladen von Bildern ist gesperrt] mit der Ausnahme eines 50k großen Forum-Avatars.


== Installation

*Vor der Installation überprüfen sie die <<bsd_license#,Lizenz>>, <<jme3/features#,Features>> und <<jme3/requirements#,Voraussetzungen>>.* Dann wählen sie eine der folgenden Optionen:
[cols="4", options="header"]
|===

a|
<a| Empfohlen
<a| Optional
<a| Optional

a| Sie möchten…
a| Eintauchen in die jMonkeyEngine
a| jMonkeyEngine mit einer anderen IDE verwenden
a| Eigene Engine aus dem Sourcecode erstellen

a| Dann laden sie…
a| link:https://github.com/jMonkeyEngine/sdk/releases[jMonkeyEngine SDK]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine/releases[Binaries]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine[Engine Sources]

a| Sie erhalten…
a| SDK, binaries, javadoc, sources
a| Binaries, javadoc, sources
a| Sources

a| Mehr erfahren hier…
a|
* <<sdk#,SDK anwenden>>
* <<sdk/project_creation#,Projekt erstellen>>
a|
* <<jme3/maven#,jME3 mit Maven und Gradle kompatiblen IDEs aufsetzen>>
* <<jme3/setting_up_netbeans_and_jme3#,jME3 in der NetBeans IDE aufsetzen>>
* <<jme3/setting_up_jme3_in_eclipse#,jME3 in der Eclipse IDE aufsetzen>>
a|
* <<jme3/build_from_sources#,jME3 aus den Sourcen erstellen>>
* <<jme3/build_jme3_sources_with_netbeans#,JME3 aus den Sourcen mit NetBeans erstellen>>
* <<jme3/simpleapplication_from_the_commandline#,JME3 an der Konsole anwenden>>

4+^a| <<jme3/jme3_source_structure#,Ein paar Worte über die Quelltextstruktur>>

|===

pass:[*] Die SDK erzeugt Ant-basierte Projekte die in jede Java IDE importiert werden können. Wir empfehlen Usern anderer IDEs zusätzlich die jMonkeyEngine SDK herunterzuladen und durch `menu:File[Import Project > External Project Assets]` ein Quellcodeloses Projekt nur für das Handling der Assets zu erstellen. Dadurch können sie in der IDE ihrer Wahl programmieren und die SDK zum konvertieren der Modelle ins .j3o format verwenden.


== Entwerfen

Nach Download und Installation, <<jme3#,erstellen sie ein Lesezeichen zur jME Doku>> und beginnen ihr erstes Spiel zu schreiben!
[cols="3", options="header"]
|===

a| Tutorials
a| jMonkeyEngine SDK
a| Sonstige Dokumentation

a| <<jme3#tutorials-für-anfänger,jME3 Anfängertutorials>>
a| <<sdk#,jMonkeyEngine SDK Dokumentation und Video Tutorials>>
a| link:{link-javadoc}[Gesamte API JavaDoc]

a| <<jme3#documentation-für-fortgeschrittene-anfänger,jME3 weiterführende Artikel>>
a| <<sdk/comic#,jMonkeyEngine SDK - Comic>>
a| <<jme3/external/blender#,Anleitung zur Modellierung in Blender>>

a| <<jme3#dokumentation-für-fortgeschrittene,jME3 fortgeschrittene Dockmentation>>
<a|
a| <<jme3/faq#,Häufig gestellte Fragen (FAQ)>>

|===


== Sich einbringen

//Are you an experienced Java developer who wants to add new features or contribute patches to the jME3 project?
Sind sie ein erfahrener Java-Entwickler und möchten dem jME3 Projekt weitere Features oder Patches hinzufügen?

*  Inpiration bisheriger <<jme3/contributions#,Beiträge>>
*  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md[Wie man sich bei jMonkeyEngine einbringt]
*  link:https://github.com/jMonkeyEngine/wiki#jmonkeyengine-documentation[Werden sie ein Wiki-Schreiber]
*  link:http://hub.jmonkeyengine.org/c/contribution-depot-jme3[Machen sie ihren Beitrag im Forum bekannt]
*  <<sdk#development,Entwickeln sie Plugins und visuelle Editoren für die jMonkeyEngine>>
*  <<report_bugs#,Fehler melden und Patches übermitteln>>
* link:https://jmonkeystore.com/[Assets finden sie im Community-betreuten jMonkeyStore]

== Kontakt

Sie sind eingeladen sich zu beteiligen und genauer über das Projekt zu informieren: Kontaktieren sie die link:https://hub.jmonkeyengine.org/badges/103/core-developer[Entwickler] oder fragen in den link:http://hub.jmonkeyengine.org/[Foren].

*  link:https://hub.jmonkeyengine.org/badges/103/core-developer[Melden sie sich beim jME Team]
**  <<team#,[Das Core Team - Wer wir sind?]>>

*  <<report_bugs#,Fehler melden>>
*  link:http://hub.jmonkeyengine.org/c/documentation-jme3[Melden sie unklare oder fehlende Dokumentation]

== Sprachen

//The team is looking for other monkeys that would be interested in a wiki translation of [insert your favorite language here].
Wir suchen andere Monkeys die das Wiki in [wählen sie eine Sprache ] übersetzen wollen.
//If you're interested in hosting translations see <<wiki\wiki_translation.adoc#,Wiki Translation Repositories>>.
Wenn sie interessiert sind und eine Übersetzung hosten wollen, lesen sie <<wiki\wiki_translation.adoc#,Wiki Übersetzungsrepositories>>

link:http://www.jmecn.net/wiki/[简体中文]
